import re

def message_probability(user_message, recognized_words, single_response = False, required_words = [], all_required = False):
    message_certainty = 0
    has_required_words = False
    
    for word in user_message:
        if word in recognized_words:
            message_certainty += 1
            
    per = float(message_certainty) / float(len(recognized_words))
    
    if all_required == False:
        for word in required_words:
            if word in user_message:
                has_required_words = True
                break
    else:
        for word in required_words:
            if word not in user_message:
                has_required_words = False
                break
            else:
                has_required_words = True
    if has_required_words or single_response:
        return int(per*100)
    else:
        return 0
    
def check_messages(message):
    highest_probability_list = {}
    
    def response(bot_response, list_of_words, single_response = False, required_words = [], all_required = False):
        nonlocal highest_probability_list
        highest_probability_list[bot_response] = message_probability(message, list_of_words, single_response, required_words, all_required)
    
    response('Hello! How can I help you today?', ['hello', 'hi', 'hey'], single_response=True)
    response('Thank you, I\'m fine. How can I help you today?', ['hello', 'hi', 'hey', 'how', 'are', 'you'], required_words=['how'])
    response('Ayurvedic treatments are a traditional system of medicine that originated in India thousands of years ago. Ayurveda is a holistic approach to health and well-being that focuses on achieving a balance between the body, mind, and spirit. The word "Ayurveda" is derived from the Sanskrit words "ayur," meaning life, and "veda," meaning knowledge, so it can be translated as the "science of life.\n\n\
Key principles and components of Ayurvedic treatments include:\n\n\
Herbal Remedies: Ayurvedic practitioners use a wide range of herbs and botanicals to create herbal remedies and supplements. These remedies are often customized to address specific health concerns or imbalances.\n\n\
Meditation and Mindfulness: Ayurveda emphasizes the importance of mental and emotional balance. Meditation and mindfulness techniques are often prescribed to reduce stress, promote mental clarity, and enhance overall well-being.\n\n\
Cleansing and Detoxification: Ayurvedic treatments include purification and detoxification practices known as "Panchakarma." These procedures are designed to eliminate toxins from the body and restore balance.\n\n\
Lifestyle Recommendations: Ayurvedic practitioners provide guidance on daily routines, sleep patterns, and lifestyle choices that align with an individual\'s dosha and promote optimal health.\n\n\
It\'s essential to note that Ayurveda is considered complementary or alternative medicine in many parts of the world, and its effectiveness can vary from person to person. If you are interested in Ayurvedic treatments, it\'s advisable to consult with a qualified Ayurvedic practitioner who can provide personalized recommendations based on your unique constitution and health concerns. Additionally, it\'s crucial to use Ayurvedic treatments in conjunction with conventional medical care, especially for serious or acute health conditions.', ['what', 'are', 'ayurvedic', 'treatments', 'ayurveda', 'diseases', 'help', 'treat'], required_words=['ayurvedic'])
    response('Ayurvedic medicine can have side effects, especially if not used properly or if the ingredients used are of poor quality. Some Ayurvedic remedies may interact with medications or cause allergic reactions in some individuals. It\'s important to consult with a qualified Ayurvedic practitioner and inform them of any existing health conditions or medications you are taking to minimize potential side effects and ensure safe use.', ['can', 'does', 'ayurveda', 'ayurvedic', 'medicine', 'have', 'side', 'effects'], required_words=['ayurvedic'])
    response('Ayurveda is not considered a primary or standalone treatment for cancer. While Ayurvedic practices may be used as complementary or supportive therapies to help manage the side effects of cancer treatments or to improve overall well-being during cancer care, they should not be used as a sole treatment for cancer. Cancer is a complex disease that typically requires conventional medical treatments such as surgery, chemotherapy, radiation therapy, immunotherapy, and targeted therapy.\n\n\
However, some people may choose to incorporate Ayurvedic practices into their overall wellness routine while undergoing cancer treatment. Ayurvedic treatments and recommendations may focus on dietary modifications, herbal supplements, yoga, meditation, and stress reduction techniques to support the individual\'s general health and quality of life during cancer treatment.\n\n\
It is crucial for anyone diagnosed with cancer to consult with a team of healthcare professionals, including oncologists and specialists, to determine the most appropriate and evidence-based treatment plan for their specific type and stage of cancer. These experts can provide guidance on integrating complementary therapies like Ayurveda safely into the overall cancer care plan.', ['is', 'there', 'ayurvedic', 'treatment', 'for', 'cancer'], required_words=['cancer'])
    response('Ayurvedic treatment for arthritis is a holistic approach that seeks to alleviate pain, reduce inflammation, and improve joint function. It encompasses a range of therapies and lifestyle modifications tailored to the individual\'s dosha constitution and the specific type of arthritis they have.\n\n\
Dietary Modifications: Ayurveda places significant emphasis on the role of diet in managing arthritis. Depending on the person\'s dosha type, an Ayurvedic practitioner may recommend specific foods to pacify aggravated doshas and reduce inflammation. Anti-inflammatory foods such as turmeric, ginger, and green leafy vegetables are often encouraged, while processed, spicy, and fried foods should be avoided.\n\n\
Herbal Remedies: Ayurvedic herbs and supplements play a crucial role in arthritis management. Some commonly used herbs for arthritis include turmeric (known for its anti-inflammatory properties), ginger, Boswellia, Ashwagandha, and Guggul. These herbs can help reduce pain and inflammation in the joints.\n\n\
Panchakarma: Panchakarma, a set of detoxification and cleansing therapies, may be recommended to remove toxins from the body. These therapies aim to reduce inflammation and improve joint mobility.\n\n\
Yoga and Gentle Exercise: Customized yoga poses and gentle exercises are designed to increase joint flexibility and reduce muscle tension. It\'s essential to avoid strenuous activities that can exacerbate arthritis symptoms.\n\n\
Meditation and Stress Reduction: Stress can worsen arthritis symptoms. Ayurveda promotes meditation and relaxation techniques to manage stress and promote overall well-being.\n\n\
Individualized treatment plans are essential in Ayurveda, as each person\'s constitution and arthritis condition may vary. It is advisable to work closely with a qualified Ayurvedic practitioner who can assess your specific needs and create a personalized treatment strategy.', ['what', 'is', 'the', 'ayurvedic', 'treatment', 'for', 'arthritis'], required_words= ['arthritis'])
    response('Ayurveda is believed to have evolved over thousands of years in ancient India, and it does not have a single attributed founder. Instead, Ayurveda is considered a body of knowledge that developed through the contributions of many ancient scholars and practitioners. Some of the foundational texts of Ayurveda, known as the "Vedas," particularly the "Rigveda" and the "Atharvaveda," contain early references to healing practices and herbal remedies.\n\n\
One of the most influential texts in Ayurveda is the "Charaka Samhita," attributed to the sage Charaka, who is often regarded as one of the founding figures of Ayurveda. Another significant text is the "Sushruta Samhita," attributed to the sage Sushruta, which focuses on surgical techniques and is particularly relevant to Ayurvedic surgery.\n\n\
While Charaka and Sushruta are prominent figures associated with Ayurveda, it\'s important to recognize that Ayurveda\'s development involved the contributions of numerous scholars, sages, and practitioners over centuries. The knowledge and practices of Ayurveda were traditionally passed down through oral tradition and written texts, making it a collective body of wisdom rather than the creation of a single individual.', ['who', 'created', 'ayurveda', 'creator', 'maker', 'person', 'individual'], required_words=['who', 'ayurveda'], all_required=True)
    response('Ayurvedic medicine is a traditional system of health care that originated in India about 3,000 years ago. It is derived from the Sanskrit words ayur (life) and veda (science or knowledge). Ayurveda is widely practiced in parts of Asia, especially in India and Nepal, where around 80% of the population report using it. Ayurveda has both preventive and curative aspects, and it adapts to the personal needs of each patient. Ayurveda uses herbal medicines, special diets, meditation, yoga, massage, and other therapies to promote health and well-being.\n\n\
        While Ayurveda originated in ancient India, it has gained recognition and popularity worldwide as a complementary and alternative system of medicine. In modern times, Ayurvedic practices, remedies, and therapies have been adapted and integrated into healthcare systems in many countries. However, it\'s important to consult with qualified Ayurvedic practitioners to ensure the safe and effective use of Ayurvedic treatments.', ['where', 'does', 'did', 'ayurveda', 'medicine', 'come', 'from', 'originate'], required_words=['where'])
    response('Ayurveda is a holistic system of medicine that originated in India and aims to balance the body, mind, and spirit. Ayurveda believes that every person has a unique constitution, or prakriti, based on the combination of three fundamental energies, or doshas. These are vata (air and space), pitta (fire and water), and kapha (earth and water) . Ayurveda diagnoses and treats diseases by identifying the imbalance of doshas and restoring harmony through natural remedies and lifestyle changes. Ayurveda also emphasizes the importance of dharma (purpose), artha (wealth), kama (pleasure), and moksha (liberation) as the four goals of human life . Ayurveda is not only a system of medicine, but also a way of living in harmony with nature and oneself.', ['what', 'is', 'ayurveda', 'definition', 'root'], required_words=['ayurveda'])
    response('The 5 Prana Vayus are the five types of vital energy that flow through the body and mind. They are:\n\n\
Prana-Vayu: The energy of intake, inspiration, and forward movement. It is located in the chest and head, and it nourishes the brain, eyes, and senses. It is associated with the heart chakra and the element of air\n\n\
Apana-Vayu: The energy of elimination, downward and outward movement. It is located in the pelvis, and it regulates the excretion of waste and toxins. It is associated with the root chakra and the element of earth\n\n\
Samana-Vayu: The energy of assimilation, discernment, and inner absorption. It is located in the navel, and it balances the digestion of food, thoughts, and emotions. It is associated with the solar plexus chakra and the element of fire\n\n\
Udana-Vayu: The energy of growth, speech, expression, and upward movement. It is located in the throat, and it supports the development of the body and mind. It is also responsible for the transition between states of consciousness. It is associated with the throat chakra and the element of space\n\n\
Vyana-Vayu: The energy of circulation, expansiveness, and pervasiveness. It is located throughout the whole body, and it distributes prana to every cell and organ. It also connects us to our surroundings and other beings. It is associated with all the chakras and all the elements\n\n\
These five Vayus work together to create harmony in our physical, mental, and spiritual health. By becoming aware of them and practicing yoga techniques that enhance their flow, we can improve our well-being and achieve higher states of awareness.', ['what', 'are', 'the', '5', 'five', 'prana', 'vayus'], required_words=['vayus'])
    response('The effectiveness of Ayurveda depends on various factors, such as the type and severity of the condition, the individual constitution of the person, the quality and safety of the Ayurvedic products, and the expertise of the practitioner. Ayurveda is considered a complementary health approach in the United States, and research on its effectiveness is limited. However, some studies have shown that Ayurvedic treatments may have some benefit for certain conditions, such as:\n\n\
Anxiety: A 2017 systematic review of 10 randomized controlled trials found that Ayurvedic interventions, such as herbal medicines, yoga, and meditation, were more effective than placebo or no intervention in reducing anxiety symptoms.\n\n\
Brain function: A 2018 randomized controlled trial of 60 healthy adults found that an Ayurvedic herbal formulation called Brahmi improved cognitive performance, attention, and working memory compared to placebo.\n\n\
High cholesterol: A 2016 systematic review of 17 randomized controlled trials found that Ayurvedic herbal medicines were more effective than placebo or conventional drugs in lowering total cholesterol, LDL cholesterol, and triglycerides.\n\n\
Osteoarthritis: A 2013 randomized controlled trial of 440 people with knee osteoarthritis found that two Ayurvedic formulations of plant extracts were as effective as glucosamine sulfate and celecoxib in reducing pain and improving function.\n\n\
These are some examples of the potential benefits of Ayurveda for certain health issues. However, more rigorous and larger-scale studies are needed to confirm the effectiveness and safety of Ayurveda for various conditions. It is important to consult with your doctor before using any Ayurvedic products or therapies, as they may interact with other medications or cause adverse effects. You should also seek qualified and reputable Ayurvedic practitioners who have adequate training and experience in this field.', ['how', 'is', 'ayurveda', 'effective', 'beneficial', 'benefits'], required_words=['effective'])
    response('Ayurveda is a holistic system of medicine that originated in India thousands of years ago. It is based on the belief that health and wellness depend on a balance between the mind, body, and spirit. Ayurveda uses natural remedies, dietary changes, lifestyle modifications, and Yoga to prevent and treat various diseases.\n\n\
The history of Ayurveda can be traced back to the ancient Vedic texts, which are the oldest scriptures of Hinduism. The word Ayurveda means “the science of life” in Sanskrit, and it is considered one of the Upavedas or sub-Vedas of the Atharvaveda. The Atharvaveda contains hymns and spells for healing and protection from diseases and evil forces.\n\n\
However, Ayurveda faced many challenges and setbacks during the colonial period when India was ruled by foreign powers. The British administration discouraged and suppressed the practice of Ayurveda and promoted Western medicine instead. Many Ayurvedic colleges and hospitals were closed down or converted into allopathic institutions. Ayurveda was also criticized for being unscientific, superstitious, and outdated by some Western-educated Indians.\n\n\
Despite these difficulties, Ayurveda survived and revived in the post-independence era with the support of the Indian government and various organizations. Ayurveda was recognized as one of the official systems of medicine in India along with allopathy, homeopathy, Unani, Siddha, and Yoga. Several institutions were established to promote research, education, regulation, and standardization of Ayurveda. Ayurveda also gained popularity in the West as an alternative or complementary form of medicine that offers natural and holistic solutions for various health problems.\n\n\
Today, Ayurveda is widely practiced in India and many other countries around the world. It is regarded as a valuable heritage of India that can contribute to the well-being of humanity. It is also a source of inspiration for many modern scientific discoveries and innovations in medicine.', ['what', 'is', 'the', 'history', 'of', 'ayurveda'], required_words=['history', 'ayurveda'], all_required=True)
    response('Dravyaguna is a branch of Ayurveda that studies the properties, effects, and actions of drugs derived from natural sources, especially plants. It is based on the principles of rasa (taste), guna (quality), virya (potency), vipaka (post-digestive effect), and prabhava (special effect) of each drug. Dravyaguna helps to understand the pharmacology and therapeutics of Ayurvedic medicine in a holistic way. Dravyaguna also deals with the identification, collection, storage, and preservation of raw materials of plant origin. Dravyaguna is an important science that contributes to the health and wellness of humanity by using natural and safe remedies.', ['what', 'is', 'dravyaguna', 'in', 'ayurveda'], required_words=['dravyaguna'])
    response('Rasayana is a term that means “the path of essence” in Sanskrit. It is a branch of Ayurveda that deals with the rejuvenation and longevity of the body and mind. Rasayana therapy uses natural herbs, minerals, diet, lifestyle, and Yoga to enhance the quality and quantity of the tissues, the vitality, the immunity, and the mental functions. Rasayana therapy also helps to prevent and cure diseases, delay aging, and promote happiness.\n\n\
Some of the benefits of Rasayana therapy are:\n\n\
It improves the digestion, metabolism, and elimination of toxins from the body.\n\
It nourishes and strengthens the organs, tissues, and cells of the body.\n\
It balances the emotions and reduces stress, anxiety, and depression.\n\
It increases the luster, complexion, and glow of the skin.\n\n\
Some of the common Rasayana herbs are:\n\n\
Amalaki (Indian gooseberry), which is rich in vitamin C and antioxidants. It rejuvenates the blood, liver, skin, eyes, and hair. It also improves digestion, immunity, and mental clarity.\n\
Ashwagandha (Indian ginseng), which is a powerful adaptogen that helps the body cope with stress. It also strengthens the muscles, nerves, bones, and reproductive system. It also enhances the stamina, energy, and libido.\n\
Brahmi (water hyssop), which is a brain tonic that improves memory, learning, and cognition. It also calms the mind and reduces anxiety, depression, and insomnia.\n\
Shatavari (wild asparagus), which is a female tonic that nourishes the reproductive organs, hormones, and milk production. It also soothes the digestive system and relieves inflammation.\n\
Yastimadhu (licorice), which is a sweet herb that soothes the throat, lungs, stomach, and intestines.\n\
Rasayana therapy can be taken in different forms such as powders, tablets, capsules, syrups, jams, oils, or ghee. Rasayana therapy should be taken under the guidance of an Ayurvedic practitioner who can prescribe the right dosage, duration, and mode of administration according to one’s age, health condition, season, and purpose.', ['what', 'is', 'rasayana', 'in', 'ayurveda'], required_words=['rasayana'])
    response('In Ayurveda, "Koshta" refers to the concept of the gastrointestinal tract or digestive system. It is a crucial aspect of Ayurvedic medicine as it plays a central role in the assimilation of nutrients, the elimination of waste, and overall health.\n\n\
The Ayurvedic perspective on Koshta emphasizes the importance of a healthy digestive system for maintaining overall well-being. According to Ayurveda, the state of the Koshta has a significant impact on a person\'s health and can influence the balance of the doshas (Vata, Pitta, Kapha) in the body.\n\
There are several factors associated with the Koshta in Ayurveda:\n\
1. Types of Koshta: Ayurveda classifies the Koshta into different types based on their characteristics and functioning. The primary types are:\n\n\
Sama Koshta: A balanced or healthy digestive system.\n\
Nirama Koshta: A depleted or weak digestive system.\n\
Prama Koshta: An aggravated or imbalanced digestive system.\n\n\
2. Agni: Agni refers to the digestive fire, which plays a central role in the Koshta. The strength of Agni determines how efficiently food is digested and metabolized. When Agni is balanced, it leads to proper digestion and absorption of nutrients.\n\n\
3. Ama: Ama is a concept in Ayurveda that refers to undigested or partially digested food toxins. When the digestive process is compromised, Ama can accumulate in the body and lead to various health issues. Maintaining a healthy Koshta helps prevent the formation of Ama.\n\n\
4. Dosha Influence: The doshas (Vata, Pitta, Kapha) can have different effects on the Koshta. For example, imbalances in Vata dosha can lead to irregular digestion and constipation, while Pitta imbalances can result in hyperacidity and inflammation in the digestive tract.\n\nA balanced Koshta is considered essential for the overall balance and harmony of the body and mind in Ayurveda. Ayurvedic practitioners often assess the state of a person\'s Koshta when diagnosing health conditions and developing treatment plans.', ['what', 'is', 'koshta', 'in', 'ayurveda'], required_words=['koshta'])
    response('Ayurveda offers a holistic approach to managing diabetes by focusing on lifestyle modifications, dietary changes, and the use of specific herbs and formulations. Here are some commonly used Ayurvedic herbs and formulations for managing diabetes:\n\n\
Bitter Melon (Momordica charantia): Bitter melon, also known as "karela" in Hindi, is known for its hypoglycemic properties. It is often consumed as a vegetable or in the form of juice or supplements.\n\n\
Fenugreek (Trigonella foenum-graecum): Fenugreek seeds are rich in soluble fiber and have been found to help control blood sugar levels. They can be consumed as seeds, sprouts, or in supplement form.\n\n\
Cinnamon (Cinnamomum verum): Cinnamon may help improve insulin sensitivity and reduce blood sugar levels. It can be added to foods or consumed as a supplement.\n\n\
Gymnema (Gymnema sylvestre): Gymnema is known as the "sugar destroyer" because it can reduce sugar cravings and block sugar absorption in the intestines. It is often used in Ayurvedic formulations for diabetes.\n\n\
Amla (Indian Gooseberry): Amla is a rich source of vitamin C and antioxidants. It may help improve insulin sensitivity and lower blood sugar levels.\n\n\
Neem (Azadirachta indica): Neem leaves and extracts have anti-diabetic properties and may help regulate blood sugar levels.\n\n\
Turmeric (Curcuma longa): Curcumin, the active compound in turmeric, has anti-inflammatory and antioxidant properties and may help improve insulin sensitivity.\n\nIt\'s crucial to work with a qualified Ayurvedic practitioner who can assess your specific condition, recommend personalized treatments, and monitor your progress. Ayurvedic treatment for diabetes is typically individualized to address the unique constitution and imbalances of each person, so what works best can vary from person to person.', ['what', 'is', 'the', 'best', 'ayurvedic', 'medicine', 'for', 'diabetes'], required_words=['diabetes'])
    response('An Ayurvedic practitioner typically asks a series of questions and conducts an assessment to determine an individual\'s Prakriti, or their inherent constitution. These questions and assessments cover a wide range of physical, mental, and emotional aspects to build a comprehensive understanding of the person\'s unique constitution. Here are some of the key elements an Ayurvedic practitioner may inquire about or evaluate:\n\n\
Physical Characteristics:\n\n\
Body type and build (e.g., slender, medium, heavy).\n\
Hair texture and color.\n\
Skin type (e.g., dry, oily, sensitive).\n\
Nail and eye characteristics.\n\
Facial features (e.g., prominent nose, lips, or chin).\n\n\
Mental and Emotional Traits:\n\n\
Personality traits (e.g., anxious, assertive, calm).\n\
Emotional tendencies (e.g., prone to anger, fear, or worry).\n\
Cognitive preferences (e.g., analytical, creative, intuitive).\n\n\
Physiological Functions:\n\n\
Appetite and digestion (e.g., strong, variable, weak).\n\
Sleep patterns (e.g., sound, light, disrupted).\n\
Energy levels (e.g., consistent, fluctuating).\n\
Elimination (e.g., regular, irregular).\n\
Temperature and Climate Preferences:\n\n\
Whether you feel more comfortable in hot or cold weather.\n\
How your body responds to changes in temperature.\n\n\
Food Preferences and Aversions:\n\n\
Cravings and aversions to specific tastes (sweet, sour, salty, pungent, bitter, astringent).\n\
Dietary habits and food choices.\n\n\
Health History:\n\n\
Any chronic health conditions or imbalances.\n\
Past illnesses or diseases.\n\
Family health history.\n\
Psychological Assessment:\n\
Assessment of psychological traits and tendencies.\n\
Stressors and sources of emotional well-being.\n\n\
Tongue Examination:\n\n\
The appearance of the tongue, including coating and color, may be examined for diagnostic purposes.\n\n\
Observation of Physical Habits:\n\n\
How you walk, talk, and move can also provide insights into your constitution.', ['what', 'happens', 'in', 'a', 'prakriti', 'assessment', 'ayurvedic', 'practitioner'], required_words=['prakriti', 'assessment'], all_required=True)
    response('Some general dietary guidelines based on the Prakriti can be given. These guidelines are a starting point but may need adjustments based on your individual constitution and imbalances:\n\n1. Vata Constitution:\n\n\
Vata individuals should favor warm, moist, and grounding foods.\n\
Include cooked, nourishing meals with a balance of all six tastes (sweet, sour, salty, pungent, bitter, astringent).\n\
Emphasize warm, easily digestible foods like cooked grains (rice, quinoa), root vegetables, and soups.\n\
Incorporate healthy fats like ghee (clarified butter) and sesame oil.\n\
Limit raw foods and cold beverages, as they can aggravate Vata.\n\
2. Pitta Constitution:\n\n\
Pitta individuals benefit from cooling, soothing, and mildly spicy foods.\n\
Choose foods with sweet, bitter, and astringent tastes to balance the heat of Pitta.\n\
Include leafy greens, grains like basmati rice, and cooling herbs like cilantro and mint.\n\
Use ghee and coconut oil in moderation.\n\
Avoid excessive spicy, oily, and fried foods.\n\n\
3. Kapha Constitution:\n\n\
Kapha individuals should focus on foods that are warm, light, and easy to digest.\n\
Emphasize pungent, bitter, and astringent tastes to counter Kapha\'s heaviness.\n\
Include plenty of vegetables, legumes, and grains like barley.\n\
Use moderate amounts of healthy fats like mustard oil.\n\
Limit dairy, sweets, and heavy, oily foods.\n\nIn addition to these dosha-specific guidelines, Ayurveda emphasizes the importance of mindful eating, eating in a calm and peaceful environment, and avoiding overeating. It\s also recommended to establish a regular eating routine and to honor your body\'s hunger and fullness cues.\n\nLastly, Ayurveda views food as medicine, and the emphasis is on promoting balance and well-being. It\'s not just about what you eat but also how you eat, when you eat, and the quality of your food. Therefore, working with a qualified Ayurvedic practitioner can provide you with a comprehensive and personalized dietary plan tailored to your unique constitution and needs.', 'what is the recommended diet based on generalized prakriti'.split(), required_words=['diet'])
    response('I can provide you with some general information about the three primary doshas (Vata, Pitta, and Kapha) and some common traits associated with each. You can use this information as a starting point for self-assessment, but for a more accurate assessment and personalized recommendations, it\'s best to consult with an Ayurvedic practitioner.\n\n\
Here\'s a brief overview of the three doshas:\n\n\
Vata Dosha:\n\n\
Physical Traits: Thin build, dry skin, cold hands and feet, delicate bones.\n\
Personality Traits: Creative, quick-thinking, adaptable, prone to anxiety.\n\
Imbalance Manifestations: Digestive issues, insomnia, anxiety, restlessness.\n\n\
Pitta Dosha:\n\n\
Physical Traits: Medium build, fair skin, sharp features, warm body temperature.\n\
Personality Traits: Intelligent, organized, driven, prone to anger when imbalanced.\n\
Imbalance Manifestations: Digestive problems, skin rashes, irritability, inflammation.\n\n\
Kapha Dosha:\n\n\
Physical Traits: Stocky build, thick hair, soft skin, strong bones.\n\
Personality Traits: Calm, patient, compassionate, prone to lethargy when imbalanced.\n\
Imbalance Manifestations: Weight gain, congestion, sluggishness, apathy.\n\n\
To determine your predominant dosha or dosha combination, you can consider your physical characteristics, personality traits, and any specific health issues you may be experiencing. Keep in mind that most people have a dominant dosha with secondary doshas to varying degrees.', 'how can I determine my dosha constitution prakriti for self assessment'.split(), required_words=['dosha', 'constitution', 'prakriti'])
    response('Determining someone\'s accurate prakriti, or Ayurvedic constitution, involves assessing a wide range of physical, mental, and emotional traits. While no single trait can definitively determine a person\'s prakriti, a combination of characteristics can provide valuable insights. Here are some traits and factors that Ayurvedic practitioners consider when assessing prakriti:\n\n\
Physical Characteristics:\n\n\
Body Build: Whether the person has a slender (Vata), medium (Pitta), or robust (Kapha) build.\n\
Skin Type: Dry or rough skin (Vata), sensitive or prone to rashes (Pitta), or smooth and oily (Kapha).\n\
Hair Texture: Fine and dry hair (Vata), medium thickness and oily (Pitta), thick and wavy (Kapha).\n\n\
Digestive System:\n\n\
Appetite: Vata individuals may have irregular appetites, Pitta individuals tend to have strong appetites, and Kapha individuals may have steady and somewhat reduced appetites.\n\n\
Mental and Emotional Traits:\n\n\
Personality: Vata individuals may be creative, adaptable, and prone to anxiety; Pitta individuals can be intelligent, organized, and sometimes prone to anger; Kapha individuals are often calm, patient, and compassionate but can become lethargic when imbalanced.\n\n\
Mental Patterns: Vata individuals may have scattered thoughts, Pitta individuals can be critical, and Kapha individuals may tend to be more stable and methodical in their thinking.\n\n\
Energy Levels:\n\n\
Assessing whether the person has bursts of energy followed by fatigue (Vata), consistent energy throughout the day (Pitta), or a slower, more steady energy (Kapha).\n\n\
Temperature Tolerance:\n\n\
Whether the person is more sensitive to cold (Vata), prefers cooler environments (Pitta), or is more sensitive to heat (Kapha).\n\n\
Response to Stress:\n\n\
How a person responds to stress, whether with anxiety (Vata), irritability (Pitta), or a desire to withdraw (Kapha).', 'How to determine my accurate prakriti dosha constitution'.split(), required_words=['accurate'])
    response('One of the ways to determine someone’s prakriti is by observing their complexion, which reflects the dominant dosha in their body. The general features of each dosha are as follows:\n\n\
Vata: Vata prakriti people have a dry, rough, thin and dark complexion. They tend to have cold and dry skin, with prominent veins and joints. Their hair is coarse, curly and brittle. They have small eyes, nose and mouth, with irregular teeth and gums. They are usually underweight and have difficulty gaining weight. They are prone to diseases related to the nervous system, bones, joints and skin.\n\n\
Pitta: Pitta prakriti people have a warm, oily, fair and radiant complexion. They tend to have soft and moist skin, with freckles, moles and acne. Their hair is fine, straight and reddish or blond. They have medium-sized eyes, nose and mouth, with sharp teeth and gums. They are usually well-built and muscular, with a strong metabolism and appetite. They are prone to diseases related to the digestive system, liver, blood and eyes.\n\n\
Kapha: Kapha prakriti people have a cold, smooth, thick and pale complexion. They tend to have oily and elastic skin, with few or no wrinkles. Their hair is thick, wavy and lustrous. They have large eyes, nose and mouth, with even teeth and gums. They are usually overweight and have difficulty losing weight. They are prone to diseases related to the respiratory system, lymphatic system, heart and kidneys.\n\nTo determine someone’s prakriti based on their complexion, one can compare their features with the above descriptions and identify the most dominant dosha in their body. However, it is important to note that most people have a combination of two or three doshas in their prakriti, which may vary in different parts of the body or at different times of life. Therefore, complexion alone may not be sufficient to determine someone’s prakriti accurately.', 'if how what is to determine prakriti dosha constitution based on my complexion dark swarthy fair'.split(), required_words=['complexion', 'dark', 'swarthy', 'fair'])
    response('Some general guidelines can be followed to get an idea of your prakriti based on your height. According to Ayurveda, the following are the typical height ranges for each dosha:\n\n\
Vata: Vata prakriti people are usually either very tall or very short, with a slender and bony frame. They have difficulty gaining weight and muscle mass. Their height range is usually above 5 feet 10 inches or below 5 feet 2 inches.\n\n\
Pitta: Pitta prakriti people are usually of medium height, with a well-proportioned and muscular body. They have a strong metabolism and appetite, and can easily gain or lose weight. Their height range is usually between 5 feet 4 inches and 5 feet 10 inches.\n\n\
Kapha: Kapha prakriti people are usually short and stocky, with a large and heavy frame. They have a slow metabolism and appetite, and tend to accumulate fat and fluids in their body. Their height range is usually below 5 feet 4 inches.\n\nTo determine your prakriti based on your height, you can compare your height with the above ranges and identify the most dominant dosha in your body. However, it is important to note that most people have a combination of two or three doshas in their prakriti, which may vary in different parts of the body or at different times of life. Therefore, height alone may not be sufficient to determine your prakriti accurately.', 'if how to what is determine prakriti constitution dosha based on my height fall into'.split(), required_words=['height', 'tall', 'short', 'average', 'giant'])
    response('Vata prakriti people are those who have a predominance of the vata dosha in their body constitution. Vata dosha is the principle of movement and governs the nervous system, the elimination process, and the creativity of the mind. Some of these characteristics are:\n\n\
They have a light, thin, and agile body frame, with dry skin, hair, and nails. They tend to be either very tall or very short, and have difficulty gaining weight and muscle mass. They have small eyes, nose, and mouth, with irregular teeth and gums. They have prominent veins and joints, and weak bones. They are prone to diseases related to the nervous system, bones, joints, and skin.\n\n\
They have a cold and dry temperament, with a preference for warm and humid climates. They have cold hands and feet, and feel excess coldness in the body. They have irregular appetite and digestion, and tend to eat small quantities of food at frequent intervals. They feel thirst moderately or sometimes excessively. They have irregular bowel movements and often suffer from constipation. They have scanty menstrual flow and dark menstrual blood.\n\n\
They have a restless and creative mind, with a tendency to wander and change. They have a quick grasping power, but a poor memory and concentration. They are easily excited, but also easily bored. They are flexible and adaptable, but also unstable and inconsistent. They are curious and eager to learn new things, but lack depth and persistence. They are imaginative and innovative, but also impractical and unrealistic.\n\n\
They have a lively and enthusiastic personality, with a flair for communication and expression. They are friendly and sociable, but also quarrelsome and untrustworthy. They are adventurous and courageous, but also careless and impulsive. They are optimistic and cheerful, but also anxious and fearful. They are generous and forgiving, but also ungrateful and untruthful.', 'what are the characteristics of vata prakriti people'.split(), required_words=['vata'])
    response('Pitta prakriti people are those who have a predominance of the pitta dosha in their body constitution. Pitta dosha is the principle of transformation and governs the metabolic activities of the body, digestion and release of energy. Some of these characteristics are:\n\n\
They have a warm, oily, fair and radiant complexion. They tend to have soft and moist skin, with freckles, moles and acne. Their hair is fine, straight and reddish or blond. They have medium-sized eyes, nose and mouth, with sharp teeth and gums. They are usually well-built and muscular, with a strong metabolism and appetite. They are prone to diseases related to the digestive system, liver, blood and eyes.\n\n\
They have a hot and fiery temperament, with a preference for cool and dry climates. They have high body temperature and sweat profusely. They have regular appetite and digestion, and tend to eat large quantities of food at regular intervals. They feel thirst frequently or excessively. They have normal bowel movements and often suffer from acidity or heartburn. They have moderate menstrual flow and bright red menstrual blood.\n\n\
They have a sharp and intelligent mind, with a tendency to analyze and criticize. They have a good grasping power, but a moderate memory and concentration. They are easily motivated, but also easily irritated. They are ambitious and competitive, but also aggressive and dominating. They are rational and practical, but also impatient and intolerant. They are confident and courageous, but also arrogant and proud.\n\n\
They have a charismatic and assertive personality, with a flair for leadership and management. They are friendly and respectful, but also argumentative and judgmental. They are adventurous and enthusiastic, but also reckless and impulsive. They are optimistic and cheerful, but also jealous and resentful. They are generous and loyal, but also possessive and controlling.', 'what are the characteristics of pitta prakriti people'.split(), required_words=['pitta'])
    response('Kapha prakriti people are those who have a predominance of the kapha dosha in their body constitution. Kapha dosha is the principle of cohesion and lubrication and governs the structure and stability of the body. Some of these characteristics are:\n\n\
They have a large and well-built body, with strong muscles and joints. They have a pleasant appearance, with a fair and smooth complexion. They have thick and lustrous hair, large and soft eyes, and a deep and pleasant voice. They tend to be overweight or obese, and have difficulty losing weight.\n\n\
They have a cold and moist temperament, with a preference for warm and dry climates. They have low body temperature and sweat little. They have regular appetite and digestion, but tend to eat more than they need. They feel thirst moderately or less. They have normal bowel movements and often suffer from mucus or congestion. They have moderate menstrual flow and pale menstrual blood.\n\n\
They have a calm and steady mind, with a tendency to preserve and maintain. They have a good memory and concentration, but a slow grasping power. They are easily contented, but also easily attached. They are loyal and supportive, but also stubborn and resistant to change. They are practical and realistic, but also complacent and dull.\n\n\
They have a friendly and compassionate personality, with a flair for socializing and nurturing. They are respectful and forgiving, but also possessive and clingy. They are adventurous and enthusiastic, but also cautious and conservative. They are optimistic and cheerful, but also sentimental and emotional. They are generous and kind, but also greedy and materialistic.', 'what are the characteristics of kapha prakriti people'.split(), required_words=['kapha'])
    response('Yes, in Ayurveda, it is absolutely possible for a person to have a combination of two doshas, such as Vata and Pitta. This is known as a dual-dosha prakriti or constitution. In fact, dual-dosha constitutions are quite common, and many people do not fit neatly into a single dosha category.\n\n\
For example, someone with a Vata-Pitta constitution would exhibit characteristics and tendencies of both Vata and Pitta doshas. They may have a combination of physical, mental, and emotional traits that reflect qualities of both doshas. Here are some general characteristics of a Vata-Pitta constitution:\n\n\
Physical Traits:\n\n\
They may have a moderate build that is not overly slender or robust.\n\
Their skin may be somewhat dry but can become sensitive or prone to redness when exposed to harsh conditions.\n\
Hair and eye color can vary but may exhibit qualities of both Vata and Pitta.\n\n\
Mental and Emotional Traits:\n\n\
They can be creative and quick-thinking like Vata individuals.\n\
They may also have a strong intellect and determination typical of Pitta individuals.\n\
Emotionally, they might experience a mix of anxiety (Vata) and irritability (Pitta) when imbalanced.\n\n\
Digestive Traits:\n\n\
Their digestion may be moderate, not too slow or too fast.\n\
They can tolerate a variety of foods but may need to be mindful of foods that aggravate both Vata and Pitta qualities.\n\nIt\'s important to note that the balance between Vata and Pitta can vary among individuals with a dual-dosha constitution. Some may have a stronger influence of one dosha over the other. Additionally, the balance of doshas can change over time due to factors like diet, lifestyle, stress, and age.', 'can a person be a combination mixture of both vata and pitta'.split(), required_words=['vata', 'pitta'], all_required=True)
    response('Yes, it is possible for a person to have a combination of both Pitta and Kapha doshas in their constitution. This is known as a dual-dosha prakriti or constitution in Ayurveda. Dual-dosha constitutions are not uncommon, and individuals often exhibit characteristics and tendencies of both doshas. When someone has a Pitta-Kapha constitution, they will have a blend of physical, mental, and emotional traits associated with both doshas. Here are some general characteristics of a Pitta-Kapha constitution:\n\n\
Physical Traits:\n\n\
They may have a moderate build that is not overly slender or robust.\n\
Their skin may be moderately oily, soft, and warm to the touch, reflecting qualities of both Pitta and Kapha.\n\
Hair and eye color can vary but may exhibit characteristics of both doshas.\n\n\
Mental and Emotional Traits:\n\n\
They can have a combination of the strong intellect and determination typically seen in Pitta individuals, along with the calm and patient qualities often associated with Kapha.\n\
Emotionally, they may experience a mix of assertiveness (Pitta) and emotional stability (Kapha) when balanced.\n\n\
Digestive Traits:\n\n\
Their digestion may be moderate, with the ability to tolerate a variety of foods.\n\
They may have a strong appetite when healthy, reflecting Pitta qualities, but they may also have a tendency to gain weight more easily due to Kapha influences.\n\n\
Just like with any dual-dosha constitution, the balance between Pitta and Kapha can vary among individuals. Some may have a stronger influence of one dosha over the other. It\'s essential to understand this balance to make appropriate dietary and lifestyle choices that support overall health and prevent imbalances associated with both Pitta and Kapha.', 'can a person be a combination of both pitta and kapha?'.split(), required_words=['pitta', 'kapha'], all_required=True)
    response('Yes, individuals can have a dual-dosha constitution that combines both Vata and Kapha characteristics in Ayurveda. This is known as a Vata-Kapha constitution, and it reflects a blend of physical, mental, and emotional traits associated with both doshas. Here are some general characteristics of a Vata-Kapha constitution:\n\n\
Physical Traits:\n\n\
They may have a body type that is neither overly thin nor excessively robust, falling somewhere in between.\n\
Skin may be moderately dry and cool to the touch (Vata influence) but also soft and somewhat oily (Kapha influence).\n\
Hair and eye color can vary but may exhibit qualities of both doshas.\n\n\
Mental and Emotional Traits:\n\n\
They can possess a blend of Vata\'s creativity and adaptability with Kapha\'s calm and patient disposition.\n\
Emotionally, they may experience a combination of anxiety or restlessness (Vata) and emotional stability (Kapha) when balanced.\n\n\
Digestive Traits:\n\n\
Their digestion may be variable, reflecting qualities of both Vata (irregular) and Kapha (steady).\n\
They may experience fluctuations in appetite, sometimes having a strong appetite and at other times feeling less hungry.\n\nAs with other dual-dosha constitutions, the balance between Vata and Kapha can vary among individuals. Some may have a stronger influence of one dosha over the other. It\'s crucial to understand this balance to make appropriate dietary and lifestyle choices that support overall health and prevent imbalances associated with both Vata and Kapha.', 'can a person be a combination of both vata and kapha'.split(), required_words=['vata', 'kapha'], all_required=True)
    response('Some general guidelines can be followed to get an idea of your prakriti based on your weight. According to Ayurveda, the following are the typical weight ranges for each dosha:\n\n\
Vata: Vata prakriti people have a low body weight and have difficulty in putting on weight. They tend to be either very tall or very short, with a slender and bony frame. They have a fast metabolism and burn calories quickly. They often skip meals or eat irregularly. They are prone to diseases related to the nervous system, bones, joints, and skin.\n\n\
Pitta: Pitta prakriti people have a medium body weight and can easily gain or lose weight. They tend to be of average height, with a well-proportioned and muscular body. They have a strong metabolism and appetite, and can digest food efficiently. They eat moderately and regularly. They are prone to diseases related to the digestive system, liver, blood, and eyes.\n\n\
Kapha: Kapha prakriti people have a high body weight and have difficulty in losing weight. They tend to be short and stocky, with a large and heavy frame. They have a slow metabolism and appetite, and tend to accumulate fat and fluids in their body. They often overeat or eat more than they need. They are prone to diseases related to the respiratory system, lymphatic system, heart, and kidneys.\n\n\
To determine your prakriti based on your weight, you can compare your weight with the above ranges and identify the most dominant dosha in your body. However, it is important to note that most people have a combination of two or three doshas in their prakriti, which may vary in different parts of the body or at different times of life. Therefore, weight alone may not be sufficient to determine your prakriti accurately.', 'how what is to determine my prakriti dosha constitution based on body weight'.split(), required_words=['weight', 'fat', 'chubby', 'slim', 'built', 'overweight'])
    response('One of the ways to determine your prakriti, or body type, according to Ayurveda is by observing your bone structure. Your bone structure reflects the dominant dosha, or energy, in your body. The three doshas are vata, pitta, and kapha, and they have different and sometimes opposite qualities. The general features of each dosha are as follows:\n\n\
Vata: Vata prakriti people have a light, small, and prominent bone structure. They tend to be either very tall or very short, with a slender and bony frame. Their joints are often visible and crack easily. They have difficulty gaining weight and muscle mass. They are prone to diseases related to the nervous system, bones, joints, and skin.\n\n\
Pitta: Pitta prakriti people have a medium and well-proportioned bone structure. They tend to be of average height, with a muscular and athletic body. Their joints are smooth and flexible. They have a strong metabolism and appetite, and can easily gain or lose weight. They are prone to diseases related to the digestive system, liver, blood, and eyes.\n\n\
Kapha: Kapha prakriti people have a large and heavy bone structure. They tend to be short and stocky, with a broad and sturdy frame. Their joints are thick and lubricated. They have a slow metabolism and appetite, and tend to accumulate fat and fluids in their body. They are prone to diseases related to the respiratory system, lymphatic system, heart, and kidneys.\n\n\
To determine your prakriti based on your bone structure, you can compare your features with the above descriptions and identify the most dominant dosha in your body. However, it is important to note that most people have a combination of two or three doshas in their prakriti, which may vary in different parts of the body or at different times of life.', 'how to determine my prakriti based on my bone structure'.split(), required_words=['bone', 'structure'], all_required=True)
    response('One of the ways to determine your prakriti is based on your skin type. Skin type is influenced by the dominant dosha in your body. Vata, pitta, and kapha have different qualities that affect the skin’s appearance, texture, color, and sensitivity. Here are some general guidelines to identify your skin type according to Ayurveda:\n\n\
Vata skin: Vata skin is dry, cool, thin, rough, and prone to wrinkles, pigmentation, and aging. It has a dark brown or black color and burns easily in the sun. Vata skin needs regular moisturizing and nourishing to prevent dehydration and cracking. People with vata skin have a quick grasping power, but a poor memory. They are creative, restless, and easily disturbed.\n\n\
Pitta skin: Pitta skin is smooth, oily, warm, soft, and sensitive. It has a white, pale, or reddish complexion and tans evenly in the sun. Pitta skin is prone to acne, rashes, inflammation, and sunburns. It needs cooling and soothing to balance the excess heat and acidity in the body. People with pitta skin are intelligent, ambitious, and assertive. They are passionate, competitive, and easily angered.\n\n\
Kapha skin: Kapha skin is oily, cold, thick, moist, and resilient. It has a light or fair color and does not tan or burn easily in the sun. Kapha skin is prone to clogged pores, blackheads, dullness, and water retention. It needs cleansing and stimulating to remove excess oil and toxins from the body. People with kapha skin are calm, loyal, and compassionate. They are stable, patient, and slow to change.\n\n\
To determine your prakriti based on your skin type more accurately, you can take an online test that asks you various questions about your physical features and preferences', 'how to determine my prakriti based on my skin'.split(), required_words=['skin'])
    response('There is no direct correlation between your hair colour and your prakriti, as hair colour can be influenced by various factors such as genetics, environment, diet, and lifestyle. However, some general trends can be observed based on the dominant dosha in your body. Here are some possible indications of your prakriti based on your hair colour:\n\n\
Vata hair: Vata hair is usually dark brown or black, thin, dry, brittle, and frizzy. It tends to lose its colour and lustre quickly and may turn grey or white prematurely. Vata hair needs regular oiling and conditioning to prevent breakage and split ends.\n\n\
Pitta hair: Pitta hair is usually light brown, blonde, or red, fine, oily, and straight. It has a natural shine and bounce, but it is also sensitive to heat and chemicals. It may become dull, thin, or fall out due to excess pitta in the body. Pitta hair needs cooling and cleansing to balance the fire element.\n\n\
Kapha hair: Kapha hair is usually black or dark brown, thick, wavy, and glossy. It has a strong and healthy growth, but it is also prone to oiliness and dandruff. It may become heavy, greasy, or limp due to excess kapha in the body. Kapha hair needs stimulating and detoxifying to remove the earth element.\n\n\
To determine your prakriti more accurately based on your hair type, you can also consider other factors such as the texture, density, curliness, and length of your hair. You can also take an online test that asks you various questions about your physical features and preferences1. You can also consult an Ayurvedic practitioner who can examine your pulse, tongue, eyes, nails, and other indicators of your dosha balance. Knowing your prakriti can help you choose the right diet, lifestyle, herbs, and treatments for your health and well-being.', 'how to determine my prakriti based on my hair colour'.split(), required_words=['hair', 'colour'], all_required=True)
    response('The appearance of your hair can give you some clues about your prakriti, or body type, according to Ayurveda. Each person has a unique combination of these doshas, which determines their prakriti.\n\n\
Your hair is influenced by the dominant dosha in your body, as well as by other factors such as genetics, diet, lifestyle, and environment. Therefore, your hair may not reflect your prakriti accurately, but it can give you some general indications. Here are some common characteristics of hair types according to the doshas:\n\n\
Vata hair: Vata is the dosha of air and space, and it is associated with movement, creativity, and change. Vata hair is usually dark brown or black, thin, dry, brittle, and frizzy. It tends to lose its colour and lustre quickly and may turn grey or white prematurely. Vata hair needs regular oiling and conditioning to prevent breakage and split ends.\n\n\
Pitta hair: Pitta is the dosha of fire and water, and it is associated with transformation, intelligence, and passion. Pitta hair is usually light brown, blonde, or red, fine, oily, and straight. It has a natural shine and bounce, but it is also sensitive to heat and chemicals. It may become dull, thin, or fall out due to excess pitta in the body. Pitta hair needs cooling and cleansing to balance the fire element.\n\n\
Kapha hair: Kapha is the dosha of earth and water, and it is associated with stability, nourishment, and compassion. Kapha hair is usually black or dark brown, thick, wavy, and glossy. It has a strong and healthy growth, but it is also prone to oiliness and dandruff. It may become heavy, greasy, or limp due to excess kapha in the body. Kapha hair needs stimulating and detoxifying to remove the earth element.\n\n\
To determine your prakriti more accurately based on your appearance of hair, you can also consider other factors such as the texture, density, curliness, and length of your hair.', 'how to determine my prakriti based on my appearance of hair'.split(), required_words=['hair', 'appearance'], all_required=True)
    response('Your face shape is influenced by the dominant dosha in your body, as well as by other factors such as genetics, diet, lifestyle, and environment. Therefore, your face shape may not reflect your prakriti accurately, but it can give you some general indications. Here are some common characteristics of face shapes according to the doshas:\n\n\
Vata face: Vata is the dosha of air and space, and it is associated with movement, creativity, and change. Vata face is usually long, angular, thin, and narrow. The forehead may be high and prominent, the nose may be crooked or pointed, the chin may be small or receding, and the cheeks may be hollow or sunken. The eyes may be small, dark, or restless. The lips may be thin and dry. Vata face needs regular moisturizing and nourishing to prevent dehydration and cracking.\n\n\
Pitta face: Pitta is the dosha of fire and water, and it is associated with transformation, intelligence, and passion. Pitta face is usually triangular or square, with sharp features and a strong jawline. The forehead may be broad or flat, the nose may be straight or sharp, the chin may be pointed or prominent, and the cheeks may be flushed or rosy. The eyes may be medium-sized, bright, or piercing. The lips may be red or pink and moist. Pitta face needs cooling and soothing to balance the excess heat and acidity in the body.\n\n\
Kapha face: Kapha is the dosha of earth and water, and it is associated with stability, nourishment, and compassion. Kapha face is usually round or oval, with soft features and a gentle expression. The forehead may be low or curved, the nose may be round or bulbous, the chin may be large or double-chinned, and the cheeks may be full or plump. The eyes may be large, calm, or dreamy. The lips may be thick and smooth. Kapha face needs cleansing and stimulating to remove excess oil and toxins from the body.', 'how to determine my prakriti based on my shape of face'.split(), required_words=['shape', 'face'], all_required=True)
    response('Your eyes are one of the features that can help you determine your prakriti, or body type, according to Ayurveda. Ayurveda is an ancient system of medicine that originated in India and is based on the concept of three doshas: vata, pitta, and kapha. These doshas are the fundamental energies that govern the physical, mental, and emotional aspects of a person. Each person has a unique combination of these doshas, which determines their prakriti.\n\nYour eyes are influenced by the dominant dosha in your body, as well as by other factors such as genetics, diet, lifestyle, and environment. Therefore, your eyes may not reflect your prakriti accurately, but they can give you some general indications. Here are some common characteristics of eye shapes according to the doshas:\n\n\
Vata eyes: Vata is the dosha of air and space, and it is associated with movement, creativity, and change. Vata eyes are usually round, blackish, and non-attractive. They may be small, dark, or restless. They tend to lose their colour and lustre quickly and may turn grey or white prematurely.\n\n\
Pitta eyes: Pitta is the dosha of fire and water, and it is associated with transformation, intelligence, and passion. Pitta eyes are usually slender, coppery, or reddish brown. They may be medium-sized, bright, or piercing. They have a natural shine and bounce, but they are also sensitive to heat and chemicals. They may become dull, thin, or fall out due to excess pitta in the body.\n\n\
Kapha eyes: Kapha is the dosha of earth and water, and it is associated with stability, nourishment, and compassion. Kapha eyes are usually white, pale, or tans evenly. They may be large, calm, or dreamy. They have a strong and healthy growth, but they are also prone to oiliness and dandruff. They may become heavy, greasy, or limp due to excess kapha in the body.\n\n\
To determine your prakriti more accurately based on your eyes, you can also consider other factors such as the color, texture, sensitivity, and hairiness of your skin', 'how to determine my prakriti based on the appearance of my eyes'.split(), required_words=['eyes', 'appearance'])
    response('Your eyelashes are another feature that can help you determine your prakriti, or body type, according to Ayurveda. Ayurveda is an ancient system of medicine that originated in India and is based on the concept of three doshas: vata, pitta, and kapha. These doshas are the fundamental energies that govern the physical, mental, and emotional aspects of a person. Each person has a unique combination of these doshas, which determines their prakriti.\n\n\
Your eyelashes are influenced by the dominant dosha in your body, as well as by other factors such as genetics, diet, lifestyle, and environment. Therefore, your eyelashes may not reflect your prakriti accurately, but they can give you some general indications. Here are some common characteristics of eyelashes according to the doshas:\n\n\
Vata eyelashes: Vata is the dosha of air and space, and it is associated with movement, creativity, and change. Vata eyelashes are usually thin, dry, brittle, and sparse. They may be dark brown or black in color and move quickly or erratically. They tend to lose their colour and lustre quickly and may fall out easily.\n\n\
Pitta eyelashes: Pitta is the dosha of fire and water, and it is associated with transformation, intelligence, and passion. Pitta eyelashes are usually fine, oily, and smooth. They may be light brown, blonde, or red in color and have a natural shine and curl. They are sensitive to heat and chemicals and may become inflamed or irritated easily.\n\n\
Kapha eyelashes: Kapha is the dosha of earth and water, and it is associated with stability, nourishment, and compassion. Kapha eyelashes are usually thick, moist, and resilient. They may be black or dark brown in color and have a long and healthy growth. They are prone to oiliness and dandruff and may become heavy or greasy easily.\n\n\
To determine your prakriti more accurately based on your eyelashes, you can also consider other factors such as the shape, size, color, and sensitivity of your eyes.', 'how to determine my prakriti based on my eyelashes'.split(), required_words=['eyelashes'])
    response('The blinking of your eyes can also help you determine your prakriti, or body type, according to Ayurveda. Ayurveda is an ancient system of medicine that originated in India and is based on the concept of three doshas: vata, pitta, and kapha. These doshas are the fundamental energies that govern the physical, mental, and emotional aspects of a person. Each person has a unique combination of these doshas, which determines their prakriti.\n\n\
Your blinking of eyes is influenced by the dominant dosha in your body, as well as by other factors such as genetics, diet, lifestyle, and environment. Therefore, your blinking of eyes may not reflect your prakriti accurately, but it can give you some general indications. Here are some common characteristics of blinking of eyes according to the doshas:\n\n\
Vata blinking: Vata is the dosha of air and space, and it is associated with movement, creativity, and change. Vata blinking is usually quick, erratic, and frequent. It may be due to dryness, nervousness, or anxiety. Vata blinking may also indicate a restless mind or a short attention span.\n\n\
Pitta blinking: Pitta is the dosha of fire and water, and it is associated with transformation, intelligence, and passion. Pitta blinking is usually moderate, steady, and regular. It may be due to concentration, focus, or curiosity. Pitta blinking may also indicate a sharp intellect or a strong willpower.\n\n\
Kapha blinking: Kapha is the dosha of earth and water, and it is associated with stability, nourishment, and compassion. Kapha blinking is usually slow, gentle, and infrequent. It may be due to relaxation, calmness, or contentment. Kapha blinking may also indicate a peaceful mind or a deep emotion.\n\n\
To determine your prakriti more accurately based on your blinking of eyes, you can also consider other factors such as the shape, size, color, and sensitivity of your eyes.', 'how to determine my prakriti based on the blinking of my eyes'.split(), required_words=['eyes', 'blinking'], all_required=True)
    response('The shape and texture of your cheeks can also help you determine your prakriti, or body type, according to Ayurveda. Ayurveda is an ancient system of medicine that originated in India and is based on the concept of three doshas: vata, pitta, and kapha. Each person has a unique combination of these doshas, which determines their prakriti.\n\n\
Your cheeks are influenced by the dominant dosha in your body, as well as by other factors such as genetics, diet, lifestyle, and environment. Therefore, your cheeks may not reflect your prakriti accurately, but they can give you some general indications. Here are some common characteristics of cheeks according to the doshas:\n\n\
Vata cheeks: Vata is the dosha of air and space, and it is associated with movement, creativity, and change. Vata cheeks are usually thin, dry, rough, and sunken. They may have dark spots, wrinkles, or pigmentation. They tend to lose their colour and lustre quickly and may crack easily. Vata cheeks need regular moisturizing and nourishing to prevent dehydration and aging.\n\n\
Pitta cheeks: Pitta is the dosha of fire and water, and it is associated with transformation, intelligence, and passion. Pitta cheeks are usually smooth, oily, warm, and flushed. They may have acne, rashes, inflammation, or sunburns. They have a natural shine and glow, but they are also sensitive to heat and chemicals. Pitta cheeks need cooling and soothing to balance the excess heat and acidity in the body.\n\n\
Kapha cheeks: Kapha is the dosha of earth and water, and it is associated with stability, nourishment, and compassion. Kapha cheeks are usually thick, moist, cold, and plump. They may have clogged pores, blackheads, dullness, or water retention. They have a strong and healthy structure, but they are also prone to oiliness and toxins. Kapha cheeks need cleansing and stimulating to remove excess oil and waste from the body.', 'how to determine my prakriti based on my cheeks'.split(), required_words=['cheeks'])
    response('The shape and size of your nose can also help you determine your prakriti, or body type, according to Ayurveda. Ayurveda is an ancient system of medicine that originated in India and is based on the concept of three doshas: vata, pitta, and kapha. Each person has a unique combination of these doshas, which determines their prakriti.\n\nYour nose is influenced by the dominant dosha in your body, as well as by other factors such as genetics, diet, lifestyle, and environment. Therefore, your nose may not reflect your prakriti accurately, but it can give you some general indications. Here are some common characteristics of nose shapes according to the doshas:\n\n\
Vata nose: Vata is the dosha of air and space, and it is associated with movement, creativity, and change. Vata nose is usually long, thin, crooked, or pointed. It may have a prominent bridge or a hump. The nostrils may be small or narrow. The tip may be dry or cracked. Vata nose needs regular oiling and moisturizing to prevent dehydration and irritation.\n\n\
Pitta nose: Pitta is the dosha of fire and water, and it is associated with transformation, intelligence, and passion. Pitta nose is usually straight, sharp, or angular. It may have a flat or moderate bridge. The nostrils may be medium-sized or wide. The tip may be red or inflamed. Pitta nose needs cooling and soothing to balance the excess heat and acidity in the body.\n\n\
Kapha nose: Kapha is the dosha of earth and water, and it is associated with stability, nourishment, and compassion. Kapha nose is usually round, bulbous, or fleshy. It may have a low or curved bridge. The nostrils may be large or flared. The tip may be moist or oily. Kapha nose needs cleansing and stimulating to remove excess oil and toxins from the body.\n\n\
To determine your prakriti more accurately based on your nose shape, you can also consider other factors such as the color, texture, sensitivity, and hairiness of your skin', 'how to determine my prakriti based on my nose'.split(), required_words=['nose'])
    response('Your teeth and gums are influenced by the dominant dosha in your body, as well as by other factors such as genetics, diet, lifestyle, and environment. Here are some common characteristics of teeth and gums according to the doshas:\n\n\
Vata teeth and gums: Vata is the dosha of air and space, and it is associated with movement, creativity, and change. Vata teeth are usually small, irregular, crooked, or spaced apart. They may have cracks, chips, or cavities. They tend to lose their colour and lustre quickly and may become sensitive to hot or cold. Vata gums are usually thin, dry, rough, and receding. They may bleed easily or become infected. Vata teeth and gums need regular oiling and moisturizing to prevent dehydration and decay.\n\n\
Pitta teeth and gums: Pitta is the dosha of fire and water, and it is associated with transformation, intelligence, and passion. Pitta teeth are usually medium-sized, regular, straight, or aligned. They may have a yellowish or reddish tint. They have a natural shine and strength, but they are also prone to heat and acidity. They may become inflamed or eroded due to excess pitta in the body. Pitta gums are usually smooth, oily, warm, and sensitive. They may have ulcers, sores, or blisters. Pitta teeth and gums need cooling and soothing to balance the excess heat and acidity in the body.\n\nKapha teeth and gums: Kapha is the dosha of earth and water, and it is associated with stability, nourishment, and compassion. Kapha teeth are usually large, regular, square, or crowded. They may have a whitish or bluish tint. They have a strong and healthy structure, but they are also prone to oiliness and toxins. They may become plaque-ridden or tartar-filled due to excess kapha in the body. Kapha gums are usually thick, moist, cold, and resilient. They may have clogged pores or swelling. Kapha teeth and gums need cleansing and stimulating to remove excess oil and waste from the body.', 'how to determine my prakriti based on my teeth and gums'.split(), required_words=['teeth', 'gums'], all_required=True)
    response('To determine your prakriti based on your lips, you need to observe the shape, size, color, texture and moisture of your lips. According to Ayurveda, there are three main types of prakriti: Vata, Pitta and Kapha. Each type has different characteristics of lips, as follows:\n\n\
Vata prakriti: Vata lips are thin, dry, rough, cracked and dark in color. They tend to get chapped easily and may have vertical lines on them. Vata people have a tendency to lick their lips frequently to moisten them. Vata lips indicate a restless, creative and sensitive personality.\n\n\
Pitta prakriti: Pitta lips are medium-sized, soft, smooth, moist and reddish in color. They may have a slight yellowish or pinkish tinge due to the heat in the body. Pitta people have a good appetite and digestion, and may experience burning sensation or mouth ulcers on their lips. Pitta lips indicate a sharp, intelligent and courageous personality.\n\n\
Kapha prakriti: Kapha lips are large, thick, plump, oily and pale in color. They may have a slight bluish or whitish hue due to the coldness in the body. Kapha people have a slow metabolism and digestion, and may experience excessive salivation or mucus on their lips. Kapha lips indicate a calm, gentle and compassionate personality.', 'how to determine my prakriti based on my lips'.split(), required_words=['lips'])
    response('One way to determine your prakriti is by observing your nails. Your nails can reveal a lot about your health, metabolism, digestion and susceptibility to diseases. Here are some general guidelines to identify your prakriti based on your nails:\n\n\
Vata prakriti: Vata nails are small, brittle, rough, dry and irregular in shape. They may have longitudinal lines or cracks on them. They are often dark or dull in color. Vata nails indicate a tendency to have poor circulation, dehydration, constipation, anxiety and nervous disorders.\n\n\
Pitta prakriti: Pitta nails are medium-sized, smooth, soft, shiny and well-shaped. They may have a reddish or pinkish hue or a yellowish tinge on them. They are often warm to touch. Pitta nails indicate a tendency to have good digestion, metabolism, intelligence and courage. They also indicate a susceptibility to inflammation, acidity, ulcers and skin problems.\n\n\
Kapha prakriti: Kapha nails are large, thick, strong, oily and round in shape. They may have a whitish or bluish hue or a pale color on them. They are often cold to touch. Kapha nails indicate a tendency to have good immunity, stamina, calmness and compassion. They also indicate a susceptibility to sluggishness, weight gain, congestion and mucus problems.', 'how to determine my prakriti based on my nails'.split(), required_words=['nails'])
    response('Your appetite can indicate the dominant dosha in your body, as each dosha has a different level and pattern of hunger and digestion. Here are some general guidelines to identify your prakriti based on your appetite:\n\n\
Vata prakriti: Vata is the dosha of air and space, and it governs movement, creativity and nervous activity. Vata people have a variable appetite, which means they can go from feeling very hungry to not hungry at all in a short span of time. They tend to eat irregularly and snack frequently. They have a weak digestion and often suffer from gas, bloating, constipation and dryness. They prefer warm, moist, nourishing and sweet foods to balance their vata.\n\n\
Pitta prakriti: Pitta is the dosha of fire and water, and it governs metabolism, intelligence and courage. Pitta people have a strong appetite, which means they feel hungry often and need to eat regularly. They have a fast digestion and can digest almost anything. They often experience heat, acidity, inflammation and ulcers in their digestive system. They prefer cool, light, bitter and astringent foods to balance their pitta.\n\n\
Kapha prakriti: Kapha is the dosha of earth and water, and it governs stability, immunity and compassion. Kapha people have a low appetite, which means they do not feel hungry easily and can skip meals without discomfort. They have a slow digestion and tend to accumulate toxins and mucus in their body. They often experience lethargy, weight gain, congestion and edema in their digestive system. They prefer hot, spicy, dry and pungent foods to balance their kapha.', 'how what to determine my prakriti do I fall into based on my appetite'.split(), required_words=['appetite', 'irregular', 'scanty', 'strong', 'unbearable', 'slow'])
    response('Each dosha is also associated with certain tastes that either increase or decrease its influence. The six tastes in Ayurveda are sweet, sour, salty, pungent, bitter and astringent. Here are some general guidelines to identify your prakriti based on your liking of tastes:\n\n\
If you like sweet, sour and salty tastes more than the other three, you may have a Kapha dominant prakriti. Kapha is the dosha of earth and water, and it governs stability, immunity and compassion. Kapha people tend to be calm, gentle, loyal and nurturing. They also tend to have a slow metabolism, weight gain, congestion and mucus problems. To balance Kapha, they should eat more of the pungent, bitter and astringent tastes, which are light, dry and stimulating.\n\n\
If you like pungent, bitter and astringent tastes more than the other three, you may have a Vata dominant prakriti. Vata is the dosha of air and space, and it governs movement, creativity and nervous activity. Vata people tend to be restless, imaginative, sensitive and enthusiastic. They also tend to have poor circulation, dehydration, constipation and anxiety problems. To balance Vata, they should eat more of the sweet, sour and salty tastes, which are warm, moist and nourishing.\n\n\
If you like all six tastes equally or have no strong preference for any of them, you may have a Pitta dominant prakriti. Pitta is the dosha of fire and water, and it governs metabolism, intelligence and courage. Pitta people tend to be sharp, confident, ambitious and competitive. They also tend to have good digestion, heat, inflammation and skin problems. To balance Pitta, they should eat more of the sweet, bitter and astringent tastes, which are cool, light and soothing.', 'how to determine my prakriti based on my liking tastes'.split(), required_words=['tastes', 'sweet', 'sour', 'salty', 'spicy', 'bitter', 'pungent', 'astringent'])
    response('Tridosha prakriti people are those who have a balanced proportion of the three doshas: vata, pitta, and kapha. They have a very stable and adaptable constitution that can tolerate a variety of environmental and dietary changes. They tend to have a medium build, good digestion, clear complexion, and strong immunity. They are also intelligent, creative, compassionate, and cheerful. However, they can also experience imbalances in any of the doshas depending on the season, lifestyle, and other factors. Therefore, they need to follow a seasonal routine that balances the dominant dosha in each season. For example, they should pacify vata in autumn and early winter, pitta in late spring and summer, and kapha in late winter and spring.', 'what are the characteristics of tridosha prakriti people'.split(), required_words=['tridosha'])
    response('Balancing your doshas is a dynamic process that entails a multifaceted strategy that includes nutrition, exercise, stress management, and lifestyle changes. Here are some general guidelines:\n\n\
Identify your dominant dosha and its qualities.\n\n\
Follow a diet that is suitable for your dosha type and the season. Eat naturally sweet, sour, and salty foods to balance vata; bitter, sweet, and astringent foods to balance pitta; and pungent, bitter, and astringent foods to balance kapha. Avoid foods that aggravate your dosha, such as spicy, dry, or cold foods for vata; sour, salty, or hot foods for pitta; and sweet, oily, or heavy foods for kapha.\n\n\
Practice yoga asanas and pranayama that are appropriate for your dosha. For example, vata types can benefit from gentle and grounding poses that calm the nervous system; pitta types can enjoy cooling and relaxing poses that release anger and frustration; and kapha types can energize themselves with stimulating and invigorating poses that increase circulation and metabolism.\n\n\
Adopt a daily routine that supports your natural rhythm and harmony. Go to bed and wake up at the same time every day, eat your meals at regular intervals, and follow a self-care regimen that includes oil massage, tongue scraping, nasal cleansing, and meditation.Avoid activities that disrupt your balance, such as staying up late, skipping meals, or overstimulating yourself with caffeine, alcohol, or media.\n\n\
Connect with nature and its elements. Spend some time outdoors every day and enjoy the beauty and healing power of nature. Vata types can benefit from walking barefoot on the earth or grass, soaking in the sun, or gazing at the stars. Pitta types can cool down by walking near a body of water, lying down on the grass, or looking at the sky. Kapha types can energize themselves by breathing fresh air, running or hiking in a park, or expanding their mind with the vastness of the universe.', 'how can I balance my dosha constitution prakriti'.split(), required_words=['balance', 'change', 'alter'])
    response('To determine your prakriti based on your dreams, you need to observe the themes, images, colors, and feelings that recur in your dreams. Different types of dreams are associated with different doshas. Here are some general guidelines to help you identify your dominant dosha from your dreams:\n\n\
Vata: This is the dosha of air and space, which governs movement, creativity, and communication. If you have a Vata dominant prakriti, you may dream of flying or rising high in the sky, climbing on mountains or trees, riding on animals like camels or elephants, seeing dried and crooked trees and rivers, or experiencing fear, anxiety, or excitement.\n\n\
Pitta: This is the dosha of fire and water, which governs digestion, metabolism, and intelligence. If you have a Pitta dominant prakriti, you may dream of seeing gold, palash and karnika trees, fire, sun, lightning, or blood, eating spicy or sour foods, feeling anger, jealousy, or pride, or being in a position of authority or leadership.\n\n\
Kapha: This is the dosha of earth and water, which governs structure, stability, and immunity. If you have a Kapha dominant prakriti, you may dream of seeing water bodies like oceans, lakes, or ponds, lotus flowers, clouds or rain, eating sweet or oily foods, feeling calm, happy, or attached, or being in a comfortable or cozy place.\n\nThese are some general suggestions for determining your prakriti based on your dreams. However, keep in mind that everyone has a unique combination of doshas in their body and mind. Therefore, it is possible to have dreams that do not match your dominant dosha. Also, your dreams may be influenced by various factors such as diet, lifestyle, stress, environment, and season.', 'How if what to is determine my prakriti i fall into based on my dreams'.split(), required_words=['dreams'])
    response('Your prakriti, or your body constitution, is determined by the balance of three doshas: Vata, Pitta, and Kapha. These doshas influence your physical and mental characteristics, including your memory. Memory, or smriti, is the ability to recall past experiences and information. According to Ayurveda, memory is influenced by various factors such as diet, lifestyle, stress, age, and prakriti.\n\n\
Different types of memory are associated with different doshas. Here are some general guidelines to help you determine your prakriti based on your memory:\n\n\
Vata: This is the dosha of air and space, which governs movement, creativity, and communication. If you have a Vata dominant prakriti, you may have a sharp but short-term memory. You can quickly grasp new concepts and ideas, but you may also forget them easily. You may have a vivid imagination and a tendency to daydream. You may also experience anxiety, insomnia, or distraction that can affect your memory.\n\n\
Pitta: This is the dosha of fire and water, which governs digestion, metabolism, and intelligence. If you have a Pitta dominant prakriti, you may have a clear and long-term memory. You can retain and recall information for a long time. You may have a logical and analytical mind and a strong sense of purpose. You may also experience anger, jealousy, or pride that can affect your memory.\n\n\
Kapha: This is the dosha of earth and water, which governs structure, stability, and immunity. If you have a Kapha dominant prakriti, you may have a slow but steady memory. You can learn and remember things gradually and deeply. You may have a calm and compassionate mind and a strong attachment to people and things. You may also experience lethargy, depression, or attachment that can affect your memory.\n\nThese are some general suggestions for determining your prakriti based on your memory.', 'how what is to determine my prakriti if i fall into based on my memory'.split(), required_words=['memory', 'memories'])
    response('Different types of mood are associated with different doshas. Here are some general guidelines to help you determine your prakriti based on your mood:\n\n\
Vata: This is the dosha of air and space, which governs movement, creativity, and communication. If you have a Vata dominant prakriti, you may have a mood that is variable, restless, and enthusiastic. You can be easily excited, inspired, or nervous. You may have a vivid imagination and a tendency to daydream. You may also experience anxiety, fear, or loneliness that can affect your mood.\n\n\
Pitta: This is the dosha of fire and water, which governs digestion, metabolism, and intelligence. If you have a Pitta dominant prakriti, you may have a mood that is stable, focused, and passionate. You can be easily motivated, confident, or ambitious. You may have a logical and analytical mind and a strong sense of purpose. You may also experience anger, jealousy, or pride that can affect your mood.\n\n\
Kapha: This is the dosha of earth and water, which governs structure, stability, and immunity. If you have a Kapha dominant prakriti, you may have a mood that is calm, steady, and compassionate. You can be easily relaxed, contented, or attached. You may have a peaceful and loving mind and a strong bond with people and things. You may also experience lethargy, depression, or attachment that can affect your mood.\n\n\
These are some general suggestions for determining your prakriti based on your mood. However, keep in mind that everyone has a unique combination of doshas in their body and mind. Therefore, it is possible to have mood traits that do not match your dominant dosha. Also, your mood may be influenced by various factors such as diet, lifestyle, stress, season, and prakriti.', 'how what is to determine my prakriti if i fall into based on my mood'.split(), required_words=['mood', 'moody'])
    response('To determine your prakriti based on your body figure, you need to understand the concept of tridosha in Ayurveda. Tridosha are the three biological energies that govern the physical and mental functions of the body. They are vata, pitta and kapha. Each person has a unique combination of these three doshas, which determines their body type or prakriti. There are seven main types of prakriti, depending on the predominance of one, two or all three doshas. They are:\n\n\
Vata: People with vata prakriti have a slim, light and angular body. They have dry, rough and cold skin, dark hair, and long or oval face. They are quick, creative, restless and enthusiastic. They tend to have poor digestion, constipation, insomnia, anxiety and nervous disorders.\n\n\
Pitta: People with pitta prakriti have a medium, muscular and well-proportioned body. They have fair, warm and oily skin, red or blond hair, and heart-shaped or pointed face. They are intelligent, ambitious, passionate and competitive. They tend to have good digestion, but also acidity, inflammation, skin rashes and anger issues.\n\n\
Kapha: People with kapha prakriti have a large, heavy and round body. They have soft, moist and cold skin, thick and curly hair, and large or round face. They are calm, loyal, compassionate and stable. They tend to have slow digestion, weight gain, congestion, lethargy and depression.', 'how what is to determine my prakriti if i fall into based on my body figure'.split(), required_words=['body', 'figure'], all_required=True)
    response('According to Ayurveda, the shape and size of your ears can indicate your dominant dosha or prakriti. Here are some general guidelines to determine your prakriti based on your ears:\n\n\
Vata: People with vata prakriti have small, thin and irregular ears. They may have prominent veins or creases on their ears. Their earlobes are detached and their ear canals are dry. They are sensitive to loud noises and cold temperatures.\n\n\
Pitta: People with pitta prakriti have medium-sized, smooth and well-shaped ears. They may have reddish or yellowish tinge on their ears. Their earlobes are attached and their ear canals are moist. They are prone to ear infections and inflammation.\n\n\
Kapha: People with kapha prakriti have large, thick and round ears. They may have oily or waxy ears. Their earlobes are fleshy and their ear canals are wet. They have good hearing and enjoy music.\n\n\
You can also observe other features of your ears, such as the angle, the curvature, the hairiness, the sensitivity and the flexibility, to get a more accurate assessment of your prakriti. For example, if your ears are tilted forward, you may have more vata in your constitution. If your ears are curved inward, you may have more pitta in your constitution. If your ears are hairy, you may have more kapha in your constitution.', 'how what is to determine my prakriti if i fall into based on my ears'.split(), required_words=['ears'])
    response('Your eyebrows can also give some clues about your prakriti or body type according to Ayurveda. Here are some general guidelines to determine your prakriti based on your eyebrows:\n\n\
Vata: People with vata prakriti have thin, sparse and irregular eyebrows. They may have gaps or breaks in their eyebrows. Their eyebrows are usually dark or black in color. They have a tendency to raise their eyebrows frequently.\n\n\
Pitta: People with pitta prakriti have medium, well-defined and arched eyebrows. They may have reddish or golden tinge in their eyebrows. Their eyebrows are usually light or brown in color. They have a tendency to frown or furrow their eyebrows often.\n\n\
Kapha: People with kapha prakriti have thick, dense and straight eyebrows. They may have bushy or unibrow eyebrows. Their eyebrows are usually soft or fair in color. They have a tendency to relax or lower their eyebrows calmly.\n\n\
You can also observe other features of your eyebrows, such as the length, the width, the angle, the hairiness, the sensitivity and the flexibility, to get a more accurate assessment of your prakriti. For example, if your eyebrows are long, you may have more vata in your constitution. If your eyebrows are short, you may have more pitta in your constitution. If your eyebrows are wide, you may have more kapha in your constitution.', 'how what is to determine my prakriti if i fall into based on my eyebrows'.split(), required_words=['eyebrows'])
    response('Your shoulders can also give some clues about your prakriti or body type according to Ayurveda. Here are some general guidelines to determine your prakriti based on your shoulders:\n\n\
Vata: People with vata prakriti have narrow, bony and angular shoulders. They may have prominent collarbones or shoulder blades. Their shoulders are usually cold, dry and rough to touch. They have difficulty in carrying heavy weights or doing strenuous activities.\n\n\
Pitta: People with pitta prakriti have medium, muscular and well-defined shoulders. They may have reddish or inflamed shoulders due to excess heat or sun exposure. Their shoulders are usually warm, oily and smooth to touch. They have good strength and endurance in their shoulders.\n\n\
Kapha: People with kapha prakriti have broad, round and fleshy shoulders. They may have oily or waxy shoulders due to excess moisture or phlegm. Their shoulders are usually cool, moist and soft to touch. They have great stability and support in their shoulders.\n\nYou can also observe other features of your shoulders, such as the height, the width, the angle, the flexibility, the sensitivity and the hairiness, to get a more accurate assessment of your prakriti. For example, if your shoulders are high, you may have more vata in your constitution. If your shoulders are low, you may have more kapha in your constitution. If your shoulders are slanted, you may have more pitta in your constitution', 'how what is to determine my prakriti if i fall into based on my shoulders shoulder'.split(), required_words=['shoulders', 'shoulder'])
    response('To determine your prakriti based on your hair type, you need to understand the concept of tridosha in Ayurveda. Tridosha are the three biological energies that govern the physical and mental functions of the body. They are vata, pitta and kapha. Each person has a unique combination of these three doshas, which determines their body type or prakriti. There are seven main types of prakriti, depending on the predominance of one, two or all three doshas. They are:\n\n\
Vata: People with vata prakriti have thin, dry and curly hair. They may have gaps or breaks in their hair. Their hair is usually dark or black in color. They have a tendency to raise their eyebrows frequently.\n\n\
Pitta: People with pitta prakriti have medium, well-defined and wavy hair. They may have reddish or golden tinge in their hair. Their hair is usually light or brown in color. They have a tendency to frown or furrow their eyebrows often.\n\n\
Kapha: People with kapha prakriti have thick, dense and straight hair. They may have bushy or unibrow hair. Their hair is usually soft or fair in color. They have a tendency to relax or lower their eyebrows calmly.', 'how what is to determine my prakriti if i fall into based on my hair type'.split(), required_words=['hair', 'thin', 'thick'])
    response('According to Ayurveda, the prakriti or body type that features scanty thirst is vata. Vata prakriti is characterized by the predominance of the vata dosha, which is the biological energy of air and space. People with vata prakriti have a slim, light and angular body. They have dry, rough and cold skin, dark hair, and long or oval face. They are quick, creative, restless and enthusiastic. They tend to have poor digestion, constipation, insomnia, anxiety and nervous disorders.\n\n\
Scanty thirst means that they do not feel thirsty often or drink enough water. This can lead to dehydration, dryness, fatigue and imbalance in their body. To balance their vata dosha, they should drink warm, herbal or spiced teas, soups, broths and juices. They should avoid cold, carbonated, caffeinated and alcoholic beverages. They should also eat moist, nourishing and warm foods, such as cooked grains, vegetables, fruits, nuts, seeds, dairy and oils. They should avoid dry, raw, light and cold foods, such as salads, popcorn, crackers, chips and frozen desserts.', 'which prakriti features scanty thirst'.split(), required_words=['thirst'])
    response('To determine your prakriti or body type based on your anxiety, you need to understand the concept of tridosha in Ayurveda. Tridosha are the three biological energies that govern the physical and mental functions of the body. They are vata, pitta and kapha. Each person has a unique combination of these three doshas, which determines their body type or prakriti. There are seven main types of prakriti, depending on the predominance of one, two or all three doshas. They are:\n\n\
Vata: People with vata prakriti have a slim, light and angular body. They have dry, rough and cold skin, dark hair, and long or oval face. They are quick, creative, restless and enthusiastic. They tend to have poor digestion, constipation, insomnia, anxiety and nervous disorders. They are more prone to vata-related diseases, such as arthritis, asthma, sciatica, neuralgia and Parkinson’s disease.\n\n\
Pitta: People with pitta prakriti have a medium, muscular and well-proportioned body. They have fair, warm and oily skin, red or blond hair, and heart-shaped or pointed face. They are intelligent, ambitious, passionate and competitive. They tend to have good digestion, but also acidity, inflammation, skin rashes and anger issues. They are more prone to pitta-related diseases, such as ulcers, gastritis, hepatitis, acne, eczema and heart disease.\n\n\
Kapha: People with kapha prakriti have a large, heavy and round body. They have soft, moist and cold skin, thick and curly hair, and large or round face. They are calm, loyal, compassionate and stable. They tend to have slow digestion, weight gain, congestion, lethargy and depression. They are more prone to kapha-related diseases, such as diabetes, obesity, asthma, bronchitis, sinusitis and hypothyroidism.', 'how what is to determine my prakriti if i fall into based on my anxiety'.split(), required_words=['anxiety'])
    response('Your anger level can also indicate your prakriti or body type according to Ayurveda. Prakriti is your unique constitution or metabolic pattern, which is determined by the combination of three doshas or biological energies: vata, pitta and kapha. Each dosha has different qualities and influences your physical, mental and emotional traits.\n\n\
Anger is a natural emotion that arises when you feel frustrated, hurt, threatened or wronged. However, how you express and manage your anger can vary depending on your prakriti. Here are some general guidelines to determine your prakriti based on your anger level:\n\n\
Vata: People with vata prakriti have a high level of vata dosha, which is the energy of air and space. They are quick, creative, restless and enthusiastic. They tend to have poor digestion, constipation, insomnia, anxiety and nervous disorders. They are more prone to vata-related diseases, such as arthritis, asthma, sciatica, neuralgia and Parkinson’s disease.\n\n\
Pitta: People with pitta prakriti have a high level of pitta dosha, which is the energy of fire and water. They are intelligent, ambitious, passionate and competitive. They tend to have good digestion, but also acidity, inflammation, skin rashes and anger issues. They are more prone to pitta-related diseases, such as ulcers, gastritis, hepatitis, acne, eczema and heart disease.\n\n\
Kapha: People with kapha prakriti have a high level of kapha dosha, which is the energy of earth and water. They are calm, loyal, compassionate and stable. They tend to have slow digestion, weight gain, congestion, lethargy and depression. They are more prone to kapha-related diseases, such as diabetes, obesity, asthma, bronchitis, sinusitis and hypothyroidism.','how what is to determine my prakriti if i fall into based on my anger levels level'.split(), required_words=['anger'])
    response('Your patience level can also indicate your prakriti or body type according to Ayurveda. Prakriti is your unique constitution or metabolic pattern, which is determined by the combination of three doshas or biological energies: vata, pitta and kapha. Each dosha has different qualities and influences your physical, mental and emotional traits.\n\n\
Patience is the ability to endure or tolerate delay, trouble, or suffering without getting angry or upset. However, how you exhibit and manage your patience can vary depending on your prakriti. Here are some general guidelines to determine your prakriti based on your patience level:\n\n\
Vata: People with vata prakriti have a low level of patience, as they are quick, creative, restless and enthusiastic. They tend to have poor digestion, constipation, insomnia, anxiety and nervous disorders. They are more prone to vata-related diseases, such as arthritis, asthma, sciatica, neuralgia and Parkinson’s disease.\n\n\
Pitta: People with pitta prakriti have a medium level of patience, as they are intelligent, ambitious, passionate and competitive. They tend to have good digestion, but also acidity, inflammation, skin rashes and anger issues. They are more prone to pitta-related diseases, such as ulcers, gastritis, hepatitis, acne, eczema and heart disease.\n\n\
Kapha: People with kapha prakriti have a high level of patience, as they are calm, loyal, compassionate and stable. They tend to have slow digestion, weight gain, congestion, lethargy and depression. They are more prone to kapha-related diseases, such as diabetes, obesity, asthma, bronchitis, sinusitis and hypothyroidism.', 'how what is to determine my prakriti if i fall into based on my patience level'.split(), required_words=['patience'])

    

    best_match = max(highest_probability_list, key=highest_probability_list.get)
    maximum = highest_probability_list[list(highest_probability_list.keys())[0]]
    for i in range(1, len(highest_probability_list)):
        if highest_probability_list[list(highest_probability_list.keys())[i]] > maximum:
            maximum = highest_probability_list[list(highest_probability_list.keys())[i]]
    print(maximum)
    return best_match

def get_response(message: str) -> str:
    p_message = re.split(r'\s+|[,;?!.-]\s*', message.lower())
    response = check_messages(p_message)
    return response


    
    

    
