questions = {
    0: "<p><strong>What is the appearance of hair?</strong></p><p>1. Dry,Black, knotted, brittle</p><p>2. Straight, oily</p><p>3. Thick, curly</p>",
    1: "<p><strong>What is your body weight?</strong><br /> 1. Low- difficulties in gaining weight<br /> 2.Moderate- no difficulties in gaining or losing weight<br /> 3.Heavy- difficulties in losing weight</p>",
    2: "<p><strong>What is your height?</strong><br /> 1.Short<br /> 2.Average<br /> 3.Tall</p>",
    3: "<p><strong>What is your bone structure?</strong><br /> 1.Light, Small- prominent joints<br /> 2.Medium, bone structure<br /> 3.Large - broad shoulders , heavy bone structure</p> ",
    4: "<p><strong>What is your complexion?</strong><br /> 1.Dark-tans easily<br /> 2.Fair- sunburns easily<br /> 3.White- pale, tans easily</p>",
    5: "<p><strong>Describe the general feel of skin-</strong><br /> 1.Dry and thin- cool to touch, rough<br /> 2.Smooth and warm, oily T-zone<br /> 3.Thick and moist-greasy, cold</p> ",
    6: "<p><strong>Describe the skin texture:</strong><br /> 1.Dry, pigments and aging<br /> 2.Freckles, many moles, redness and rashes<br /> 3.Oily</p> ",
    7: "<p><strong>What is your hair colour?</strong><br /> 1.Black/Brown,dull<br /> 2.Red, light brown, yellow<br /> 3.Brown</p>",
    8: "<p><strong>Describe the appearance of your hair:</strong></p> <p>1.Dry, black, knotted, brittle</p <p>2.Straight, oily</p> <p>3.Thick, curly</p>",
    9: "<p><strong>Describe the shape of face:</strong></p> <p>1.Long, angular, thin</p> <p>2.Heart-shaped, pointed chin</p> <p>3.Large, round, full</p>",
    10: "<p><strong>Describe your eyes:</strong></p> <p>1.Small, active, darting, dark eyes</p> <p>2.Medium-sized, penetrating, light-sensitive eyes</p> <p>3.Big, round, beautiful, glowing eyes</p> ",
    11: "<p><strong>Describe your eyelashes:</strong></p><p>1.Scanty eyelashes</p><p>2.Moderate eyelashes</p><p>3.Thick/Fused eyelashes</p>",
    12: "<p><strong>How often do you blink your eyes?</strong></p> <p>1.Excessive Blinking</p> <p>2.Moderate Blinking</p> <p>3.More or less stable</p>",
    13: "<p><strong>How are your cheeks?</strong></p> <p>1.Wrinkled, Sunken</p> <p>2.Smooth, Flat</p> <p>3.Rounded, Plump</p>",
    14: "<p><strong>How is your nose?</strong></p> <p>1.Crooked, Narrow</p> <p>2.Pointed, Average</p> <p>3.Rounded, Large open nostrils</p>",
    15: "<p><strong>Describe your teeth and gums:</strong></p> <p>1.Irregular, Protruding teeth, Receding gums</p> <p>2.Medium-sized teeth, Reddish gums</p> <p>3.Big, White, Strong teeth, Healthy gums</p>",
    16: "<p><strong>How are your lips?</strong></p> <p>1.Tight, thin, dry lips which chaps easily</p> <p>2.Lips are soft, medium-sized</p> <p>3.Lips are large, soft, pink, and full</p>",
    17: "<p><strong>How are your nails?</strong></p> <p>1.Dry, Rough, Brittle, Break</p> <p>2.Sharp, Flexible, Pink, Lustrous</p> <p>3.Thick, Oily, Smooth, Polished</p> ",
    18: "<p><strong>What is your appetite like?</strong></p> <p>1.Irregular, Scanty</p> <p>2.Strong, Unbearable</p> <p>3.Slow but steady</p> ",
    19: "<p><strong>What are some of your likable tastes?</strong></p> <p>1.Sweet / Sour / Salty</p> <p>2.Sweet / Bitter / Astringent</p> <p>3.Pungent / Bitter / Astringent</p>",
}
