import os
import nltk
from nltk.tokenize import sent_tokenize
from weasyprint import HTML
from logger import logger

# nltk.download("punkt")


def createHTMLListString(text: str) -> str:
    """Converts the paragraph into a Unorderedlist HTML Tag.

    Args:
        text (str): Paragraph to be converted into a unorderedlist.

    Returns:
        str: Paragraph converted into a unorderedlist.
    """
    text: list[str] = sent_tokenize(text)
    text.insert(0, "<ul>")
    text.insert(len(text), "</ul>")
    for i in range(1, len(text)-1):
        text[i] = f"<li>{text[i]}</li>"
    text = "".join(text)
    return text


def createPDF(consume: str, avoid: str, dosha: str) -> bytes:
    html_content = f"""
<html>
<head>
    <title>Your Prakriti - AyurInsights</title>
</head>
<body>
    <header>
        <div>
            <center>
                <img src="https://ucarecdn.com/56c57686-f88c-471d-8b0e-f7b6b70ee7a4/-/preview/300x189/" alt="Logo">
            </center>
        </div>
    </header>
    <div>
        <h2 style="text-align: center;">Your Prakriti is : {dosha}</h2>
        <div class="table-result">
            <div style="font-size: 20px;font-weight: bold;text-align: center;text-decoration-line: underline;">Diet
                Recommendation</div>
            <div>
                <h3>To Consume: </h6>
                    <div style="text-align: justify;">
                        {createHTMLListString(consume)}
                    </div>
            </div>
            <div>
                <h3>To Avoid: </h3>
                <div style="text-align: justify;">
                    {createHTMLListString(avoid)}
                </div>
            </div>
        </div>
    </div>
    <footer style="padding-top: 17px;">
        <div style="padding:14px 0px; color:gray; text-align: center;">
            <b>Disclaimer : </b>The dietary recommendations provided above have been curated and tested by Ayurvedic
            experts.
        </div>
        <div style="padding: 8px;border: 2px solid black ;">
            <b>Note:</b> This document has been automatically generated by <a
                href="http://localhost:5173">AyurInsights</a>. You can also discover your prakriti by visiting and
            answering a set of questions.
        </div>
        <div style="text-align: center;padding-top: 18px;font-weight: bold;font-size:18px">
            Thank You 🙏🙏 For Using our Website and Our Services.
        </div>
    </footer>
</body>
</html>"""
    pdf = HTML(string=html_content).write_pdf()
    logger.info("Created PDF File")
    return pdf
